# MySQL database file

development:
  adapter: mysql2
  encoding: utf8
  database: insolent_squeegee
  host: localhost
  pool: 5
  username: insolent
  password: Password1

# Test environment
test:
  adapter: mysql2
  encoding: utf8
  database: insolent_squeegee_test
  pool: 5
  user: insolent
  password: Password1

production:
  adapter: mysql2
  encoding: utf8
  database: insolent_squeegee_production
  pool: 5
  user: insolent
  password: Password1
